atividades/urls.py
from django.contrib import admin
from django.urls import path
# from .views import ActivityListView
# from .views import activity_list, activity_create
from .views import (ActivityCreateView,
                    ActivityDetailView,
                    ActivityDeleteView,
                    ActivityListView,
                    ActivityListAllView,
                    ActivityDefaultUpdateView,
                    ActivitySessionUpdateView,
                    ActivityMaterialUpdateView,
                    ActivityLocationUpdateView,
                    ConfigActivityView,
                    ConfigActivityCreateView,
                    ConfigActivityUpdateView,
                    MaterialListView,
                    MaterialUpdateView,
                    MaterialCreateView,
                    MaterialCreateView2,
                    MaterialDeleteView,
                    ThemeCreateView,
                    ThemeCreateView2,
                    ThemeListView,
                    ThemeDetailView,
                    ThemeUpdateView,
                    ThemeDeleteView,
                    load_buildings,
                    load_location,
                    delete_session,
                    delete_material,
                    activity_detail_info,
                    get_duration,
                    change_status,
                    modal_fill,
                    load_free_location,
                    request_change,
                    FORMS, )

from .forms import MaterialForm

app_name = 'activity'


urlpatterns = [
    # atividades
    path('', ActivityListView.as_view(), name = 'activity'),
    path('todas/', ActivityListAllView.as_view(), name = 'activity-all'),
    path('propor/', ActivityCreateView.as_view(FORMS), name = 'activity-create'),
    path('<int:pk>/', ActivityDetailView.as_view(), name='activity-detail'),
    path('<int:pk>/delete/', ActivityDeleteView.as_view(), name='activity-delete'),
    path('<int:pk>/updateinfo/', ActivityDefaultUpdateView.as_view(), name='activity-update-default'),
    path('<int:pk>/updatesession/', ActivitySessionUpdateView.as_view(), name = 'activity-session-update'),
    path('<int:pk>/updatematerial/', ActivityMaterialUpdateView.as_view(), name = 'activity-material-update'),
    path('<int:pk>/updatelocation/', ActivityLocationUpdateView.as_view(), name = 'activity-location-update'),

    # config
    path('config/', ConfigActivityView.as_view(), name = 'config-activity'),
    path('config/nova', ConfigActivityCreateView.as_view(), name = 'config-create'),
    path('config/atualizar/', ConfigActivityUpdateView.as_view(), name = 'config-update'),

    # temas
    path('tema/', ThemeListView.as_view(), name='theme-list'),
    path('tema/criar/', ThemeCreateView.as_view(), name='theme-create'),
    path('tema/criartema/', ThemeCreateView2.as_view(), name='theme-create-theme'),
    path('tema/<int:pk>/', ThemeDetailView.as_view(), name='theme-detail'),
    path('tema/<int:pk>/alterar/', ThemeUpdateView.as_view(), name='theme-update'),
    path('tema/<int:pk>/eliminar/', ThemeDeleteView.as_view(), name='theme-delete'),

    # materiais
    path('material/criar/', MaterialCreateView.as_view(), name='material-create'),
    path('material/criarmaterial/', MaterialCreateView2.as_view(), name='material-create-material'),
    path('material/', MaterialListView.as_view(), name='material-list'),
    path('material/<int:pk>/eliminar/', MaterialDeleteView.as_view(), name='material-delete'),
    path('material/<int:pk>/alterar/', MaterialUpdateView.as_view(), name='material-update'),

    #ajax paths
    path('ajax/load-buildings/', load_buildings, name='ajax_load_buildings'),  # <-- this one here
    path('ajax/load-location/', load_location, name='ajax_load_location'),  # <-- this one here
    path('ajax/delete-session/', delete_session, name='ajax_delete-session'),
    path('ajax/delete-material/', delete_material, name='ajax_delete-material'),
    path('ajax/activity_detail_info/',  activity_detail_info, name='ajax_detail-info'),
    path('ajax/change_status/', change_status, name='ajax_change-activity-status'),
    path('ajax/modal_fill/', modal_fill, name='ajax_modal-fill'),
    path('ajax/load_free_location/', load_free_location, name='ajax_load-free-location'),
    path('ajax/get_duration/', get_duration, name='ajax_get-duration'),
    path('ajax/request_change/', request_change, name='ajax_request-change'),
]

config_dia_aberto/urls.py
from django.urls import path

from . import views

app_name = 'config_dia_aberto'
urlpatterns = [
    # path('config/', views.ConfigListView.as_view(), name='config-list'),
    path('config/', views.config_detail_view, name='config'),
    path('config/criar/', views.ConfigCreateView.as_view(), name='config-create'),
    path('config/alterar/', views.config_update_view, name='config-update'),
    # path('config/<int:pk>/delete/', views.ConfigDeleteView.as_view(), name='config-delete'),


    path('contactos/criar/', views.contact_create_view, name='contact-create'),

    path('contactos/email/<int:pk>/alterar/', views.ContactEmailUpdateView.as_view(), name='contact-email-update'),
    path('contactos/email/<int:pk>/eliminar/', views.ContactEmailDeleteView.as_view(), name='contact-email-delete'),

    path('contactos/telefone/<int:pk>/alterar/', views.ContactTelephoneUpdateView.as_view(), name='contact-telephone-update'),
    path('contactos/telefone/<int:pk>/eliminar/', views.ContactTelephoneDeleteView.as_view(), name='contact-telephone-delete'),

    path('contactos/localizacao/<int:pk>/alterar/', views.ContactLocaleUpdateView.as_view(), name='contact-locale-update'),
    path('contactos/localizacao/<int:pk>/eliminar/', views.ContactLocaleDeleteView.as_view(), name='contact-locale-delete'),

    path('transportes/', views.UniTransportListView.as_view(), name='transport-list'),
    # path('transport/<int:pk>/', views.UniTransportDetailView.as_view(), name='transport-detail'),
    path('transportes/criar/', views.UniTransportCreateView.as_view(), name='transport-create'),
    path('transportes/<int:pk>/alterar/', views.UniTransportUpdateView.as_view(), name='transport-update'),
    path('transportes/<int:pk>/eliminar/', views.UniTransportDeleteView.as_view(), name='transport-delete'),
    path('transportes/publicar/', views.UniTransportPublishView.as_view(), name='transport-publish'),


    path('refeicoes/', views.MealListView.as_view(), name='meal-list'),
    path('refeicoes/criar/', views.MenuCreateView.as_view(), name='meal-create'),
    path('refeicoes/<int:pk>/alterar/', views.MenuUpdateView.as_view(), name='meal-update'),
    path('refeicoes/<int:pk>/eliminar/', views.delete_meal, name='meal-delete'),
    path('refeicoes/precos/', views.delete_meal, name='meal-prices'),


    #config meals
    path('refeicoes/config/', views.ConfigMealListView.as_view(), name="config-meal-list"),
    path('refeicoes/config/criar/', views.ConfigMealCreateView.as_view(), name="config-meal-create"),
    path('refeicoes/config/update/', views.ConfigActivityUpdateView.as_view(), name="config-meal-update"),
]

dia_aberto/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from .sitemap import StaticViewSitemap
from django.conf.urls import url


sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [

    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    path('', include('inscricao.urls')),
    path('', include('users.urls')),
    path('atividades/', include('atividades.urls')),
    path('', include('config_dia_aberto.urls')),
    path('notificacoes/', include('notificacoes.urls')),
    path('', include('coordenadores.urls')),
    path('colaboradores/', include('colaboradores.urls')),
]

inscricao/urls.py
from django.contrib import admin
from django.urls import path
from .views import (viewInscricao, viewInscricao2,home, viewInscricao3, viewInscricao4, viewInscricao5, viewInscricao6)

urlpatterns = [
    path('', home, name = "home"),
    path('viewInscricao', viewInscricao, name = 'viewInscricao'),
    path('viewInscricao/<int:pk_test>/', viewInscricao2, name = 'idnome'),
    path('viewInscricao2/<str:pk_test>/', viewInscricao3, name = 'idnome2'),
    path('viewInscricao3/<str:pk_test>/', viewInscricao4, name = 'idnome3'),
    path('viewInscricao4/<str:pk_test>/', viewInscricao5, name = 'idnome4'),
    path('viewInscricao5/<str:pk_test>/', viewInscricao6, name = 'idnome5'),
    # path('inscricao', inscricao.as_view(FORMS), name = 'inscricao'),
    # path('InscricaoUpdateView', InscricaoUpdateView.as_view(), name = 'InscricaoUpdateView'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from  . import views

from users.views import *


urlpatterns = [
	#path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('login/', MyLogin, name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
	path('register/', UserFormView.as_view(), name='register'),
	path('register/update/<int:pk>/', UserUpdateView, name='register_update'),
	path('perfil/criar/', ProfileCreateView.as_view(), name='profile_add'),
	path('perfil/update/<int:pk>/', ProfileUpdateView.as_view(), name='profile_update'),

	#
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/registration/password_reset_form.html', email_template_name = 'users/registration/password_reset_email.html', subject_template_name = 'users/registration/password_reset_subject.txt'), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/registration/password_reset_done.html'), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/registration/password_reset_confirm.html'), name='password_reset_confirm'),    
	path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/registration/password_reset_complete.html'), name='password_reset_complete'),

	#path('add_profile/', AddProfileView.as_view(), name='add_profile'),
	#
	path('perfil/administrador/', views.ProfAdminCreate, name='perfil_admin'),
	path('perfil/cordenador/', views.ProfCordenadorCreate, name='perfil_cordenador'),
	path('perfil/professor/', views.ProfProfessorCreate, name='perfil_professor'),
	path('perfil/colaborador/', views.ProfcolaboradorCreate, name='perfil_colaborador'),
	path('perfil/participante/', views.ProfileParticipanteCreate, name='perfil_participante'),

	#
	path('utilizadores/', views.UtilizadoresList, name='utilizadores_list'),
   #path('utilizadores/utilizador_list/', TemplateView.as_view(template_name="users/utilizador_list.html"), name='utilizador_list'),
	path('utilizadores/visualizar/<int:pk>/', UtilizadorDetailView.as_view(), name='detail'),
	path('utilizadores/apagar/<int:pk>/', UtilizadorDeleteView.as_view(), name='delete'),
	path('utilizadores/editar/<int:pk>/', UtilizadorUpdateView, name='update'),
	path('utilizadores/update_estado/<int:pk>/', update_estado, name='update_estado'),
	#
	path('list_profile/', ProfileListView.as_view(), name='list_profile'),
	path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
	#
	path('usuario/', views.UserProfileView, name='user_profile'),
	path('usuario/password_change/', change_password, name='password_change'),
	path('usuario/apagar/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
	path('usuario/editar', views.UserProfileEditView, name='user_profile_edit'),
	path('usuario/update/<int:pk>/', views.UsuarioUpdateView, name='usuario_update'),
	path('usuario/update_perfil/<int:pk>/', Usuario2UpdateView.as_view(), name='usuario2_update'),
	path('usuario/criar_perfil/<int:pk>/', Usuario2CreateView.as_view(), name='usuario2_profile'),
	
	#
	path('update_group/<int:pk>/', GroupUpdateView.as_view(), name='update_group'),
	path('delete_group/<int:pk>/', GroupDeleteView.as_view(), name='delete_group'),
	#
	path('participante/criar/', ParticipantCreateView.as_view(), name='add_participant'),
	#path('add_individual_participant/', IndividualParticipantCreateView.as_view(), name='add_individual_participant'),
	#path('add_participant_group/', ParticipantGroupCreateView.as_view(), name='add_participant_group'),
	#path('panel_of_participant/', ParticipantGroupCreateView.as_view(), name='panel_of_participant'),
	#path('participant_group_add/', ParticipantGroupCreateView.as_view(), name='participant_group_add'),
	#path('secondary_teacher_add/', SecondaryTeacherCreateView.as_view(), name='secondary_teacher_add'),
	#
	path('colaborador/criar/', ColaboratorCreateView.as_view(), name='colaborator_add'),
	path('colaborador/schedule/', ScheduleColaboratorCreateView.as_view(), name='add_schedule_colaborator'),
	#path('colaborador/update/<int:pk>/', ColaboratorUpdateView.as_view(), name='colaborator_update'),
	

	#path('colaborator_list/', ColaboratorListView.as_view(), name='colaborator_list'),
	#
	#path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
	path('docente/criar/', TeacherCreateView.as_view(), name='teacher_add'),
	#
  
	path('cordenador/criar', CoordinatorCreateView.as_view(), name='coordinator_add'),
	#
	path('administrador/criar/', AdministratorCreateView.as_view(), name='administrator_add'),

	#
	path('administrador/update_estado/<int:pk>/', update_estado_adm, name='update_estado_adm'),
    path('professor/update_estado/<int:pk>/', update_estado_tch, name='update_estado_tch'),
	path('colaborador/update_estado/<int:pk>/', update_estado_colab, name='update_estado_colab'),
	path('coordenador/update_estado/<int:pk>/', update_estado_coord, name='update_estado_coord')



]

inscricao/forms.py
from django.forms import *
from django import forms
from . models import *
from atividades.models import Session
from config_dia_aberto.models import Config
from django.urls import reverse_lazy
from datetime import datetime, date, timedelta

class ResponsavelForm(ModelForm):
    class Meta:
        model = Responsavel
        fields = ['name', 'email', 'phone']

class ParticipantForm(ModelForm):
	class Meta:
		model = Participant
		fields = ['user', 'area', 'school_year']
		widgets = {
			'school_year': NumberInput(attrs={'class': 'numberinput form-control', 'min':'9', 'max':'12'})
		}

class ParticipantGroupForm(ModelForm):
    class Meta:
        model = Participant_Group
        fields = ['n_participants']
        widgets = {
            'n_participants': NumberInput(attrs={'class': 'numberinput form-control', 'min':'1', 'max':'1000'})
        }

class SchoolForm(ModelForm):

	class Meta:
		model = School
		fields = ['name', 'address', 'zip', 'city']


class MealAmmountForm(ModelForm):

	class Meta:
		model = MealAmmount
		exclude = ['sub']


class TimeWidget(TimeInput):

    def __init__(self, attrs=None, format=None, input_type='time'):
        if input_type is not None:
            self.input_type=input_type
        if attrs is not None:
            self.attrs = attrs.copy()
        else:
            self.attrs = {'class': 'textinput textInput form-control'}
        if format is not None:
            self.format = format
        else: 
            self.format = '%H:%M'

class TransportForm(Form):
	TRANSPORT_CHOICES = [
		('Transport_Uni', 'Transporte da Universidade'),
		('Carro', 'Carro'),
		('Comboio', 'Comboio'),
		('Autocarro', 'Autocarro'),
	]
	transport_type = ChoiceField(choices=TRANSPORT_CHOICES, widget=Select(attrs={'class': 'textinput textInput form-control'}))
	transport_entry = CharField(widget=TimeWidget())
	transport_exit = CharField(widget=TimeWidget())
	
class SubscriptionForm(ModelForm):
	class Meta:
		model = Subscription
		exclude = ['date']

class SessionForm(ModelForm):
	class Meta:
		model = Session
		fields = '__all__'

class SubscriptionSessionAtivitiyForm(ModelForm):
    class Meta:
        model = SubscriptionSessionAtivitiy
        exclude = ['own_transport']

inscricao/templates/inscricao/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load sass_tags %}
<head>
	{% comment %} meta headers {% endcomment %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<link rel="icon" href="{% static 'img/logo.png' %}"/>

	<title>Dia Aberto - {% block title %}{% endblock title %}</title>

	{% comment %} Bootstrap core CSS {% endcomment %}
	<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'vendor/bulma/style.min.css' %}" rel="stylesheet">

	{% comment %} googleapis and fontawesome {% endcomment %}
	<link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">

	{% comment %} glyphicons {% endcomment %}

	<script src="https://kit.fontawesome.com/ecb927371c.js" crossorigin="anonymous"></script>

	{% comment %} Custom SCSS styles for this template {% endcomment %}
	<link href="{% sass_src 'scss/dia_aberto.scss' %}" rel="stylesheet">

	{% comment %} if other templates require more css {% endcomment %}
	{% block extrahead %}
	{% endblock extrahead %}

</head>

<body>

{% comment %} top navbar section {% endcomment %}
{% comment %} Navigation  {% endcomment %}
<nav class="navbar pb-0 pt-0 fixed-top navbar-expand-lg navbar bg-white fixed-top" style="height:50px">
	<div class="container-fluid p-0 m-0">
		{% comment %} logo {% endcomment %}
		<div class="navbar-brand">
			<a class="navbar-item logo router-link-exact-active router-link-active" href="{% url 'home' %}"><img src="{% static 'img/logo-navbar.png' %}" alt='dia-aberto' style="height:30px; width:auto"></a>
		</div>
		{% comment %} collapsed bar screen {% endcomment %}
		<button class="navbar-toggler collapsed  navbar-toggle navbar-toggler-right"id="ChangeToggle" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar top-bar"></span>
			<span class="icon-bar middle-bar"></span>
			<span class="icon-bar bottom-bar"></span>
		</button>
		{% comment %} menu options {% endcomment %}
		<div class="collapse navbar-collapse" id="navbarResponsive">

			<ul class="navbar-nav">
				{% comment %} only admin sees a different name for this link, everyone else sees the other other one {% endcomment %}
				{% if request.user.administrator %}
					<li><a class="navbar-item is-tab router-link" href="{% url 'config_dia_aberto:config'%}">Configurações do Dia Aberto</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'activity:config-activity'%}">Configurações de Atividade</a></li>

				{% else %}
					<li><a class="navbar-item is-tab router-link" href="{% url 'config_dia_aberto:config'%}">Dia Aberto</a></li>
				{% endif %}

				{% if request.user.administrator %}
					<li><a class="navbar-item is-tab router-link" href="{% url 'activity:activity'%}">Atividades</a></li>
					{% if request.user.teacher%}
						<li><a class="navbar-item is-tab router-link" href="{% url 'activity:theme-list' %}?view=all">Temas</a></li>
						<li><a class="navbar-item is-tab router-link" href="{% url 'activity:material-list' %}?view=all">Materiais</a></li>
					{% endif %}
					<li><a class="navbar-item is-tab router-link" href="{% url 'config_dia_aberto:transport-list'%}">Transportes</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'config_dia_aberto:meal-list'%}">Refeições</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'viewInscricao' %}">Inscrições</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'utilizadores_list'%}">Utilizadores</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'listacolaboradores'%}">Consultar Colaboradores</a></li>
				{% elif request.user.coordinator %}
					<li><a class="navbar-item is-tab router-link" href="{% url 'activity:activity'%}">Atividades</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'activity:activity' %}?view=all">Todas as Atividades</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'listacolaboradores'%}">Consultar Colaboradores</a></li>
					{% if request.user.teacher%}
						<li><a class="navbar-item is-tab router-link" href="{% url 'activity:theme-list' %}?view=all">Temas</a></li>
						<li><a class="navbar-item is-tab router-link" href="{% url 'activity:material-list' %}?view=all">Materiais</a></li>
					{% endif %}
					<li><a class="navbar-item is-tab router-link" href="{% url 'task' %}">Tarefas</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'utilizadores_list'%}">Utilizadores</a></li>
				{% elif request.user.teacher %}
					<li><a class="navbar-item is-tab router-link" href="{% url 'activity:activity'%}">Atividades</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'activity:activity' %}?view=all">Todas as Atividades</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'activity:theme-list' %}?view=all">Temas</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'activity:material-list' %}?view=all">Materiais</a></li>
				{% elif request.user.colaborator %}
					<li><a class="navbar-item is-tab router-link" href="{% url 'colaborador' request.user.colaborator.id %}">Consultar tarefas</a></li>
				{% elif request.user.participant %}
					<li><a class="navbar-item is-tab router-link" href="{% url 'config_dia_aberto:transport-list'%}">Transportes</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'activity:activity' %}?view=all">Todas as Atividades</a></li>
					<li><a class="navbar-item is-tab router-link" href="{% url 'config_dia_aberto:meal-list'%}">Refeições</a></li>
					<li><a class="navbar-item is-tab router-link" href="/viewInscricao/{{getID}}">Consultar A Minha Inscrição</a></li>
					{% comment %} <li><a class="navbar-item is-tab router-link" href="{% url 'inscricao' %}">Criar Inscrição</a></li> {% endcomment %}
				{% else  %}
					<!--if user not loged-->
				{% endif%}
			</ul>

			{% comment %} Login / notificações /perfil {% endcomment %}
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
				{% comment %} notificações {% endcomment %}
				{% include 'notificacoes/notification_nav_menu.html' %}

				<li class="nav-link dropdown">
					<button class="nav-link" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="user-badge" href="">
							<i class="fas fa-user"></i>
					</button>
					 <div class="user dropdown-menu dropdown-menu-right" aria-labelledby="user-badge">
						<h4 class="dropdown-header"><strong>{{ user.get_username }}</strong></h4>
						<p class="dropdown-divider"></p>
						<a class="dropdown-item" href="{% url 'user_profile'%}">Perfil</a>
					</div>
				{% endif %}
				{% comment %} login/logout {% endcomment %}
				<li class="nav-link float-right login-logout-button ">
				{% if user.is_authenticated %}
					<a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i>Sair</a>
				{% else %}
					<a class="nav-link " href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i>Login</a>
				{% endif %}
				</li>
			</ul>
		</div>
	</div>
</nav>
{% comment %} end navbar {% endcomment %}

{% comment %} body {% endcomment %}
<section id="front-page-section" class="pt-1" style="width:100%, position: absolute; height: 100%;background: linear-gradient(to bottom, #3273dc 0%,#3273dc 50%,#f8f9fa 50%,#f8f9fa 100%)">
{% block content %}
{% endblock content%}
</section>
{% comment %} end body {% endcomment %}




{% comment %} footer {% endcomment %}
{% comment %} <footer class="bg-white d-flex " style="bottom:-49px;justify-content: space-between">
	<div class="">
		(c) 2020
	</div>
	<div class="">
		Dia Aberto
	</div>
	<div class="">
		not stolened'nt
	</div>
</footer> {% endcomment %}
{% comment %} end footer {% endcomment %}

{% comment %} Bootstrap core JavaScript  {% endcomment %}


{% block loader%}
{% endblock loader%}

{% comment %} modal popups go here {% endcomment %}
{% block modals %}
{% endblock modals %}


<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

{% comment %} Plugin JavaScript  {% endcomment %}
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/dia_aberto.js' %}"></script>

{% comment %} notification navbar logic {% endcomment %}
<script src="{% static 'js/notification_nav.js' %}"></script>

{% comment %} Custom Scripts {% endcomment %}
{% comment %} <script src="{% static 'js/dia_aberto.js'%}"></script> {% endcomment %}
{% block extrajs %}
{% endblock extrajs %}
</body>
</html>

inscricao/templates/inscricao/base_with_container.html
{% extends 'inscricao/base.html' %}
{% load static %}
{% block content %}
{% comment %} fancy container {% endcomment %}

<div class=" p-0 container-fluid ml-auto mr-auto">
    <div class="card index-content">
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb bg-white">
                {% block path%}
                <li class="breadcrumb-item active" aria-current="page">Início</li>
                {% endblock %}
            </ul>
        </nav>
        <section id="messages-section">
        {% if messages %}
            {% for message in messages %}
            <div id="message_container" {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert" {% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}
        </section>
        {% block content_card %}
        {% endblock content_card %}
    </div>
</div>
{% comment %} fancy container {% endcomment %}
{% endblock content %}

inscricao/templates/inscricao/inscricao_field_set_1.html
{% extends 'inscricao/inscricao_form.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block fieldset %}
<fieldset>
<div class="form-card text-left">
<form method="POST" enctype="multipart/form-data">
    <h2 class="fs-title">Informação da Atividade</h2>
    {{ aform|crispy }}
    {% csrf_token %}
   <button type="submit" name="next" class="next action-button" value="Next Step">next</button>
</form>
</div>
</fieldset>
{% endblock %}