config_dia_aberto/urls.py
from django.urls import path

from . import views

app_name = 'config_dia_aberto'
urlpatterns = [
    # path('config/', views.ConfigListView.as_view(), name='config-list'),
    path('config/', views.config_detail_view, name='config'),
    path('config/criar/', views.ConfigCreateView.as_view(), name='config-create'),
    path('config/alterar/', views.config_update_view, name='config-update'),
    # path('config/<int:pk>/delete/', views.ConfigDeleteView.as_view(), name='config-delete'),


    path('contactos/criar/', views.contact_create_view, name='contact-create'),

    path('contactos/email/<int:pk>/alterar/', views.ContactEmailUpdateView.as_view(), name='contact-email-update'),
    path('contactos/email/<int:pk>/eliminar/', views.ContactEmailDeleteView.as_view(), name='contact-email-delete'),

    path('contactos/telefone/<int:pk>/alterar/', views.ContactTelephoneUpdateView.as_view(), name='contact-telephone-update'),
    path('contactos/telefone/<int:pk>/eliminar/', views.ContactTelephoneDeleteView.as_view(), name='contact-telephone-delete'),

    path('contactos/localizacao/<int:pk>/alterar/', views.ContactLocaleUpdateView.as_view(), name='contact-locale-update'),
    path('contactos/localizacao/<int:pk>/eliminar/', views.ContactLocaleDeleteView.as_view(), name='contact-locale-delete'),

    path('transportes/', views.UniTransportListView.as_view(), name='transport-list'),
    # path('transport/<int:pk>/', views.UniTransportDetailView.as_view(), name='transport-detail'),
    path('transportes/criar/', views.UniTransportCreateView.as_view(), name='transport-create'),
    path('transportes/<int:pk>/alterar/', views.UniTransportUpdateView.as_view(), name='transport-update'),
    path('transportes/<int:pk>/eliminar/', views.UniTransportDeleteView.as_view(), name='transport-delete'),
    path('transportes/publicar/', views.UniTransportPublishView.as_view(), name='transport-publish'),


    path('refeicoes/', views.MealListView.as_view(), name='meal-list'),
    path('refeicoes/criar/', views.MenuCreateView.as_view(), name='meal-create'),
    path('refeicoes/<int:pk>/alterar/', views.MenuUpdateView.as_view(), name='meal-update'),
    path('refeicoes/<int:pk>/eliminar/', views.delete_meal, name='meal-delete'),
    path('refeicoes/precos/', views.delete_meal, name='meal-prices'),


    #config meals
    path('refeicoes/config/', views.ConfigMealListView.as_view(), name="config-meal-list"),
    path('refeicoes/config/criar/', views.ConfigMealCreateView.as_view(), name="config-meal-create"),
    path('refeicoes/config/update/', views.ConfigActivityUpdateView.as_view(), name="config-meal-update"),
]

dia_aberto/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from .sitemap import StaticViewSitemap
from django.conf.urls import url


sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [

    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    path('', include('inscricao.urls')),
    path('', include('users.urls')),
    path('atividades/', include('atividades.urls')),
    path('', include('config_dia_aberto.urls')),
    path('notificacoes/', include('notificacoes.urls')),
    path('', include('coordenadores.urls')),
    path('colaboradores/', include('colaboradores.urls')),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from  . import views

from users.views import *


urlpatterns = [
	#path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('login/', MyLogin, name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
	path('register/', UserFormView.as_view(), name='register'),
	path('register/update/<int:pk>/', UserUpdateView, name='register_update'),
	path('perfil/criar/', ProfileCreateView.as_view(), name='profile_add'),
	path('perfil/update/<int:pk>/', ProfileUpdateView.as_view(), name='profile_update'),

	#
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/registration/password_reset_form.html', email_template_name = 'users/registration/password_reset_email.html', subject_template_name = 'users/registration/password_reset_subject.txt'), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/registration/password_reset_done.html'), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/registration/password_reset_confirm.html'), name='password_reset_confirm'),    
	path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/registration/password_reset_complete.html'), name='password_reset_complete'),

	#path('add_profile/', AddProfileView.as_view(), name='add_profile'),
	#
	path('perfil/administrador/', views.ProfAdminCreate, name='perfil_admin'),
	path('perfil/cordenador/', views.ProfCordenadorCreate, name='perfil_cordenador'),
	path('perfil/professor/', views.ProfProfessorCreate, name='perfil_professor'),
	path('perfil/colaborador/', views.ProfcolaboradorCreate, name='perfil_colaborador'),
	path('perfil/participante/', views.ProfileParticipanteCreate, name='perfil_participante'),

	#
	path('utilizadores/', views.UtilizadoresList, name='utilizadores_list'),
   #path('utilizadores/utilizador_list/', TemplateView.as_view(template_name="users/utilizador_list.html"), name='utilizador_list'),
	path('utilizadores/visualizar/<int:pk>/', UtilizadorDetailView.as_view(), name='detail'),
	path('utilizadores/apagar/<int:pk>/', UtilizadorDeleteView.as_view(), name='delete'),
	path('utilizadores/editar/<int:pk>/', UtilizadorUpdateView, name='update'),
	path('utilizadores/update_estado/<int:pk>/', update_estado, name='update_estado'),
	#
	path('list_profile/', ProfileListView.as_view(), name='list_profile'),
	path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
	#
	path('usuario/', views.UserProfileView, name='user_profile'),
	path('usuario/password_change/', change_password, name='password_change'),
	path('usuario/apagar/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
	path('usuario/editar', views.UserProfileEditView, name='user_profile_edit'),
	path('usuario/update/<int:pk>/', views.UsuarioUpdateView, name='usuario_update'),
	path('usuario/update_perfil/<int:pk>/', Usuario2UpdateView.as_view(), name='usuario2_update'),
	path('usuario/criar_perfil/<int:pk>/', Usuario2CreateView.as_view(), name='usuario2_profile'),
	
	#
	path('update_group/<int:pk>/', GroupUpdateView.as_view(), name='update_group'),
	path('delete_group/<int:pk>/', GroupDeleteView.as_view(), name='delete_group'),
	#
	path('participante/criar/', ParticipantCreateView.as_view(), name='add_participant'),
	#path('add_individual_participant/', IndividualParticipantCreateView.as_view(), name='add_individual_participant'),
	#path('add_participant_group/', ParticipantGroupCreateView.as_view(), name='add_participant_group'),
	#path('panel_of_participant/', ParticipantGroupCreateView.as_view(), name='panel_of_participant'),
	#path('participant_group_add/', ParticipantGroupCreateView.as_view(), name='participant_group_add'),
	#path('secondary_teacher_add/', SecondaryTeacherCreateView.as_view(), name='secondary_teacher_add'),
	#
	path('colaborador/criar/', ColaboratorCreateView.as_view(), name='colaborator_add'),
	path('colaborador/schedule/', ScheduleColaboratorCreateView.as_view(), name='add_schedule_colaborator'),
	#path('colaborador/update/<int:pk>/', ColaboratorUpdateView.as_view(), name='colaborator_update'),
	

	#path('colaborator_list/', ColaboratorListView.as_view(), name='colaborator_list'),
	#
	#path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
	path('docente/criar/', TeacherCreateView.as_view(), name='teacher_add'),
	#
  
	path('cordenador/criar', CoordinatorCreateView.as_view(), name='coordinator_add'),
	#
	path('administrador/criar/', AdministratorCreateView.as_view(), name='administrator_add'),

	#
	path('administrador/update_estado/<int:pk>/', update_estado_adm, name='update_estado_adm'),
    path('professor/update_estado/<int:pk>/', update_estado_tch, name='update_estado_tch'),
	path('colaborador/update_estado/<int:pk>/', update_estado_colab, name='update_estado_colab'),
	path('coordenador/update_estado/<int:pk>/', update_estado_coord, name='update_estado_coord')



]

config_dia_aberto/forms.py
from django import forms
from django.db.models import TextChoices
from django.utils.translation import gettext_lazy as _
from django.forms import inlineformset_factory
from django.db.utils import ProgrammingError
from django.core.exceptions import ValidationError


from bootstrap_datepicker_plus import DateTimePickerInput

# from dateutil.relativedelta import relativedelta
# from crispy_forms.helper import FormHelper
from intl_tel_input.widgets import IntlTelInputWidget
from localflavor.pt.forms import PTZipCodeField
from localflavor.pt import pt_regions

from .models import (
    Config,
    ConfigMeal,
    Contact,
    ContactEmail,
    ContactTelephone,
    ContactLocale,
    UniTransport,
    Menu,
    Meal,
)


class ConfigForm(forms.ModelForm):
    class Meta:
        model = Config
        fields = [
            'title', 'description',
            'start_datetime', 'end_datetime',
            'activity_limit_subscription_start_datetime',
            'activity_limit_subscription_end_datetime',
            'participant_limit_subscription_start_datetime',
            'participant_limit_subscription_end_datetime'
        ]

    def clean(self, *args, **kwargs):
        cleaned_data = super().clean()
        validation_errors = {}
        if cleaned_data.get('end_datetime') <= cleaned_data.get('start_datetime'):
            validation_errors['end_datetime'] = ValidationError(_('O fim do Dia Aberto tem que ser depois do início do Dia Aberto.'), code='invalid')
        if cleaned_data.get('activity_limit_subscription_end_datetime') <= cleaned_data.get('activity_limit_subscription_start_datetime'):
            validation_errors['activity_limit_subscription_end_datetime'] = ValidationError(_('O fim da proposição de atividades tem que ser depois do início da proposição de atividades.'), code='invalid')
        elif cleaned_data.get('activity_limit_subscription_end_datetime') > cleaned_data.get('participant_limit_subscription_start_datetime'):
            validation_errors['activity_limit_subscription_end_datetime'] = ValidationError(_('O período de proposição de atividades não pode terminar depois do começo das inscrições ao Dia Aberto.'), code='invalid')
        if cleaned_data.get('participant_limit_subscription_end_datetime') <= cleaned_data.get('participant_limit_subscription_start_datetime'):
            validation_errors['participant_limit_subscription_end_datetime'] = ValidationError(_('O fim da inscrição ao Dia Aberto tem que ser depois do início da inscrição ao Dia Aberto.'), code='invalid')
        elif cleaned_data.get('participant_limit_subscription_end_datetime') > cleaned_data.get('start_datetime'):
            validation_errors['participant_limit_subscription_end_datetime'] = ValidationError(_('O período de inscrições ao Dia Aberto não pode terminar depois do começo do Dia Aberto.'), code='invalid')

        if validation_errors:
            raise ValidationError(validation_errors)


class ContactForm(forms.Form):
    class ContactType(TextChoices):
        TELEPHONE = 'TELEPHONE', _('Telefone')
        EMAIL = 'EMAIL', _('Correio Eletrónico')
        LOCALE = 'LOCALE', _('Localização')

    contact_type = forms.ChoiceField(choices=ContactType.choices, label='Tipo de contacto', widget=forms.RadioSelect())


class ContactEmailForm(forms.ModelForm):
    class Meta:
        model = ContactEmail
        fields = ['email']


class ContactTelephoneForm(forms.ModelForm):
    class Meta:
        model = ContactTelephone
        fields = ['telephone']
        widgets = {
            'telephone': IntlTelInputWidget(preferred_countries=['pt', 'es', 'gb'], default_code='pt'),
        }


class ContactLocaleForm(forms.ModelForm):
    # zip_code = PTZipCodeField(label='Código Postal')
    region = forms.ChoiceField(label='Região', initial=pt_regions.REGION_CHOICES[7], choices=pt_regions.REGION_CHOICES)

    class Meta:
        model = ContactLocale
        # fields = ['address', 'region', 'zip_code']
        fields = ['address', 'region']


# TRANSPORTS forms #
################################################################################

class UniTransportForm(forms.ModelForm):
    class Meta:
        model = UniTransport
        fields = ['name_identifier', 'transport_type',
                  'from_location', 'destination_location',
                  'departure_datetime']

    def clean_destination_location(self):
        data_from = self.cleaned_data['from_location']
        data = self.cleaned_data['destination_location']

        if data == data_from:
            raise ValidationError(_('Destino não pode ser igual a origem'))

        return data

# MEALS form #
################################################################################

class MenuFormSet(forms.ModelForm):
    class Meta:
        model = Menu
        fields = [
            'date',
        ]




class MealFormSet(forms.ModelForm):
    class Meta:
        model = Meal
        fields = [
            'meal_type',
            'name',
            'description',
        ]

class ConfigMealForm(forms.ModelForm):
    class Meta:
        model = ConfigMeal
        fields = [
            'normal_prof_price',
            'normal_student_price',
            'eco_prof_price',
            'eco_student_price',
        ]

MenuForm = inlineformset_factory(Menu, Meal, fields=('name', 'meal_type',))

config_dia_aberto/templates/config_dia_aberto/config.html
{% extends 'inscricao/base_with_container.html' %}
{% load static %}
{% load sass_tags %}
{% load filter_is_user_types %}

{% block title %}Configurações do Dia Aberto{% endblock %}

{% block extrahead %}
{% endblock %}

{% block path %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}">Início</a></li>
    {% if request.user|is_user_types:"Administrator" %}
    <li class="breadcrumb-item active" aria-current="page">Configuração do Dia Aberto</li>
    {% else %}
    <li class="breadcrumb-item active" aria-current="page">Dia Aberto</li>
    {% endif %}
{% endblock %}

{% block content_card %}
<div class="mb-5 pb-5 pl-5 pr-5">
  <div class="row">
    <div class="col-sm-12 col-md-6 col-lg-9">
      {% if request.user|is_user_types:"Administrator" %}
      <h2 class="title is-3">Configurações do Dia Aberto</h2>
      {% else %}
      <h2 class="title is-3">Dia Aberto</h2>
      {% endif %}
    </div>
    {% if request.user|is_user_types:"Administrator" %}
    <div class="col-sm-12 col-md-6 col-lg-3">
      <a class="button is-link is-medium" href="{% url 'config_dia_aberto:config-update' %}" type="button"><i class="text-white fas fa-pencil-alt pr-2"></i>Alterar Configuração</a>
    </div>
    {% endif %}
  </div>
  <div class="border-top mt-2 pt-2 ml-5 mr-5">
    <h3 class="subtitle is-4">Dados</h3>
    <table class="table table-striped table-sm col-6">
      <tbody>
        <tr>
          <th scope="row">Título:</th>
          <td>{{ config.title }}</td>
        </tr>
        <tr>
          <th scope="row">Descrição:</th>
          <td>{{ config.description }}</td>
        </tr>
      </tbody>
    </table>

    <h3 class="subtitle is-4">Datas Limite</h3>
    <table class="table table-striped table-sm col-8">
      <tbody>
        <tr>
          <th scope="row">Data de início do Dia Aberto:</th>
          <td>{{ config.start_datetime }}</td>
        </tr>
        <tr>
          <th scope="row">Data de fim do Dia Aberto:</th>
          <td>{{ config.end_datetime }}</td>
        </tr>
        <tr>
          <th scope="row">Data de início da inscrição de participantes:</th>
          <td>{{ config.participant_limit_subscription_start_datetime }}</td>
        </tr>
        <tr>
          <th scope="row">Data de fim da inscrição de participantes:</th>
          <td>{{ config.participant_limit_subscription_end_datetime }}</td>
        </tr>
        <tr>
          <th scope="row">Data de início da proposição de atividades:</th>
          <td>{{ config.activity_limit_subscription_start_datetime }}</td>
        </tr>
        <tr>
          <th scope="row">Data de fim da proposição de atividades:</th>
          <td>{{ config.activity_limit_subscription_end_datetime }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="container mt-5 pt-2">
    <div class="row">
      <div class="col">
        <h2 class="title is-4">Contactos</h2>
      </div>
      {% if request.user|is_user_types:"Administrator" %}
      <div class="col-8">
        <a class="button is-success" href="{% url 'config_dia_aberto:contact-create' %}" type="button"><i class="text-white fas fa-plus fa-sm pr-2"></i>Criar Contacto</a>
      </div>
      {% endif %}
    </div>
    <div class="container">
      <div class="row mt-3 mb-2">
        <div class="col">
          <h4 class="subtitle">Telefone</h4>
        </div>
      </div>
      {% if contacts_telephone %}
        <table class="table table-striped table-sm col-8">
          {% for contact_telephone in contacts_telephone %}
            <tr>
              <td style="width: 85%">{{ contact_telephone.telephone }}</td>
              {% if request.user|is_user_types:"Administrator" %}
              <td>
                <a href="{% url 'config_dia_aberto:contact-telephone-update' contact_telephone.pk %}" data-toggle="tooltip" data-placement="top" title="Alterar"><i class="fas fa-pencil-alt"></i></a>
                <a href="{% url 'config_dia_aberto:contact-telephone-delete' contact_telephone.pk %}" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="text-danger fas fa-trash-alt"></i></a>
              </td>
              {% endif %}
            </tr>
          {% endfor %}
        </table>
      {% else %}
        <p>Ainda não foram adicionados contactos telefónicos.</p>
      {% endif %}
    </div>
    <div class="container">
      <div class="row mt-3 mb-2">
        <div class="col">
          <h4 class="subtitle">E-mail</h4>
        </div>
      </div>
      {% if contacts_email %}
        <table class="table table-striped table-sm col-8">
          {% for contact_email in contacts_email %}
            <tr>
              <td style="width: 85%">{{ contact_email.email }}</td>
              {% if request.user|is_user_types:"Administrator" %}
              <td>
                <a href="{% url 'config_dia_aberto:contact-email-update' contact_email.pk %}" data-toggle="tooltip" data-placement="top" title="Alterar"><i class="fas fa-pencil-alt"></i></a>
                <a href="{% url 'config_dia_aberto:contact-email-delete' contact_email.pk %}" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="text-danger fas fa-trash-alt"></i></a>
              </td>
              {% endif %}
            </tr>
          {% endfor %}
        </table>
      {% else %}
        <p>Ainda não foram adicionados contactos por correio eletrónico.</p>
      {% endif %}
    </div>
    <div class="container">
      <div class="row mt-3 mb-2">
        <div class="col">
          <h4 class="subtitle">Localização</h4>
        </div>
      </div>
      {% if contacts_locale %}
        <table class="table table-striped table-sm col-8">
          {% for contact_locale in contacts_locale %}
            <tr>
              <td style="width: 85%">
              {% for num, region in pt_regions %}
                {% if num == contact_locale.region  %}
                  {{ region }}, {{ contact_locale.address }}
                {% endif %}
              {% endfor %}
              </td>
              {% if request.user|is_user_types:"Administrator" %}
              <td>
                <a href="{% url 'config_dia_aberto:contact-locale-update' contact_locale.pk %}" data-toggle="tooltip" data-placement="top" title="Alterar"><i class="fas fa-pencil-alt"></i></a>
                <a href="{% url 'config_dia_aberto:contact-locale-delete' contact_locale.pk %}" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="text-danger fas fa-trash-alt"></i></a>
              </td>
              {% endif %}
            </tr>
          {% endfor %}
        </table>
      {% else %}
        <p>Ainda não foram adicionadas localizações.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

<!--extra js-->
{% block extrajs %}
<script type="text/javascript">
  $(document).ready(function () {
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>
{% endblock extrajs %}

config_dia_aberto/templates/config_dia_aberto/config_missing.html
{% extends 'inscricao/base_with_container.html' %}
{% load static %}
{% load sass_tags %}
{% load filter_is_user_types %}

{% block title %}Configurações do Dia Aberto{% endblock %}

{% block extrahead %}
{% endblock %}

{% block path %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}">Início</a></li>
    {% if request.user|is_user_types:"Administrator" %}
    <li class="breadcrumb-item active" aria-current="page">Configuração do Dia Aberto</li>
    {% else %}
    <li class="breadcrumb-item active" aria-current="page">Dia Aberto</li>
    {% endif %}
{% endblock %}

{% block content_card %}
<div class="mb-5 pb-5 pl-5 pr-5">
  {% if request.user|is_user_types:"Administrator" %}
  <h2 class="title is-3">Configurações do Dia Aberto</h2>
  {% else %}
  <h2 class="title is-3">Dia Aberto</h2>
  {% endif %}
  <div class="container border-top mt-2 pt-2">
    <br>
    <h3 class="subtitle is-4">Configuração em falta</h3>
    <br>
    {% if request.user|is_user_types:"Administrator" %}
      {% if request.GET.next %}
      <a class="button is-success is-medium" href="{% url 'config_dia_aberto:config-create' %}?next={{ request.GET.next }}" type="button"><i class="text-white fas fa-plus pr-2"></i>Criar Configuração</a>
      {% else %}
      <a class="button is-success is-medium" href="{% url 'config_dia_aberto:config-create' %}" type="button"><i class="text-white fas fa-plus pr-2"></i>Criar Configuração</a>
      {% endif %}
    {% endif %}
  </div>
</div>
{% endblock %}

<!--extra js-->
{% block extrajs %}
{% endblock extrajs %}

config_dia_aberto/templates/config_dia_aberto/configmeal_form.html
{% extends 'inscricao/base_with_container.html' %}

{% load bootstrap4 %}
{% load static %}
{% load sass_tags %}

{% block title %}Configurar Definições das Refeições do Dia Aberto{% endblock %}

{% block extrahead %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% endblock %}

{% block path %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}">Início</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'config_dia_aberto:meal-list' %}">Refeições</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'config_dia_aberto:config-meal-list' %}">Configuração do Dia Aberto</a></li>
    <li class="breadcrumb-item active" aria-current="page">Nova Configuração</li>
{% endblock %}


{% block content_card %}
<div class="mb-5 pb-5 pl-5 pr-5 col-xs-12 col-sm-12 col-md-12 col-lg-6">
  <h2 class="title is-3">Configurações das Refeições do Dia Aberto</h2>
  <div class="container-fluid border-top mt-2 pt-2">
   <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="subtitle is-4">Preços</legend>
        {% bootstrap_form form %}
      </fieldset>
      <div class="form-group">
        <a class="button is-dark" href="../">Cancelar</a>
        <button class="button is-link" type="submit">Submeter</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

<!--extra js-->
{% block extrajs %}
{% endblock extrajs %}

config_dia_aberto/templates/config_dia_aberto/configmeal_list.html
{% extends 'inscricao/base_with_container.html' %}
{% load static %}
{% load sass_tags %}
{% load filter_is_user_types %}

{% block title %}Configurar definições das Refeições do Dia Aberto{% endblock %}

{% block extrahead %}
{% endblock %}

{% block path %}
  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}">Início</a></li>
  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'config_dia_aberto:meal-list' %}">Refeições</a></li>
  <li class="breadcrumb-item active" aria-current="page">Configuração das Refeições</li>
{% endblock %}

{% block content_card %}
<div class="mb-5  pl-5 pr-5 pb-5">
  <div class="row">
    <div class="col-9">
      <h2 class="title is-3">Configurações das Refeições do Dia Aberto</h2>
    </div>
    {% if meal %}
    {% if request.user.is_authenticated and request.user|is_user_types:"Administrator" %}
    <div class="col-3">
      <a class="button is-link is-medium" href="{% url 'config_dia_aberto:config-meal-update' %}" type="button"><i class="text-white fas fa-pencil-alt pr-2"></i>Alterar Configuração</a>
    </div>
    {% endif %}
  </div>
  <div class="container-fluid border-top mt-2 pt-2">
   <h3 class="subtitle is-4">Preços das Refeições </h3>
    <table class="table table-striped table-sm col-6">
      <tbody>
        <tr>
            <td>Preço normal para docente</td>
            <td>{{ meal.normal_prof_price }} </td>
        </tr>
        <tr>
            <td>Preço normal para estudante</td>
            <td>{{ meal.normal_prof_price }} </td>
        </tr>
        <tr>
            <td>Preço económico para docente</td>
            <td>{{ meal.eco_prof_price }} </td>
        </tr>
        <tr>
            <td>Preço económico para estudante</td>
            <td>{{ meal.eco_prof_price }} </td>
        </tr>
      </tbody>
    </table>
    </div>
    {% else %}
    </div>
       <br>
    <h3 class="subtitle is-4">Configuração em falta</h3>
    <br>
    {% if request.user.is_authenticated and request.user|is_user_types:"Administrator" %}
      <a class="button is-success is-medium" href="{% url 'config_dia_aberto:config-meal-create' %}" type="button">Criar Configuração</a>
    {% endif %}
    {% endif %}
  </div>
</div>
{% endblock %}

<!--extra js-->
{% block extrajs %}
{% endblock extrajs %}

config_dia_aberto/templates/config_dia_aberto/menu_list_not_ready.html
{% extends 'inscricao/base_with_container.html' %}
{% load static %}
{% load sass_tags %}
{% load filter_is_user_types %}


{% block title %}Refeições{% endblock title %}




{% block extrahead %}
{% endblock extrahead %}






{% block path %}
  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}">Home</a></li>
  <li class="breadcrumb-item active" aria-current="page">Refeições</li>
{% endblock path %}








{% block content_card %}
<div id="meals-list" class="mb-5 pb-5 pl-5 pr-5">
  <h2 class="title is-3">Refeições</h2>
  <hr>
  <ul>
    <h4>O período do dia aberto ainda não está definido</h4>
    {% if request.user.is_authenticated and request.user|is_user_types:"Administrator" %}
      As datas ainda não estão configuradas. <a href="{% url 'config_dia_aberto:config' %}">Clique aqui para fazer as configurações</a>.
    {% endif %}
  </ul>
</div>
{% endblock %}







<!--extra js-->
{% block extrajs %}
{% endblock extrajs %}