dia_aberto/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from .sitemap import StaticViewSitemap
from django.conf.urls import url


sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [

    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    path('', include('inscricao.urls')),
    path('', include('users.urls')),
    path('atividades/', include('atividades.urls')),
    path('', include('config_dia_aberto.urls')),
    path('notificacoes/', include('notificacoes.urls')),
    path('', include('coordenadores.urls')),
    path('colaboradores/', include('colaboradores.urls')),
]

notificacoes/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

app_name = "notificacoes"
urlpatterns = [
    path('inbox', inboxView, name="viewInbox"),
    path('<int:pk>/markAsSeen', markAsSeen, name='markAsSeen'),
    path('<int:pk>/setPriority', setPriority, name='setPriority'),
    path('<int:pk>/resetPriority', resetPriority, name='resetPriority'),
    path('<int:pk>/delete', deleteNtf, name='deleteNtf'),
    path('sendMessage', sendMessage, name="sendMessage"),
    path('notificacoeslist2', notificacoes1, name='notificacoes'),
    path('countNew', getCountNew, name='getCountNew'),
    path('updateLastFetch', updateLastFetch, name='updateLastFetch'),
    path('getLastNotifications', getLastNotifications, name='getLastNotifications'),
    path('getAllRecievedNotifications', getAllRecievedNotifications, name='getAllRecievedNotifications'),
    path('getAllSentNotifications', getAllSentNotifications, name='getAllSentNotifications'),
    path('getNotificationData/<int:pk>', getNotificationData, name='getNotificationData'),
    path('sendMessageForm', sendMessageForm, name="sendMessageForm"),
    path('responseMessage/<int:pk>', responseMessage, name="responseMessage"),
    path('responseMessageForm', responseMessageForm, name="responseMessageForm"),
    path('Sended', seeAllSended, name='Sended'),
    path('DeleteNotifications/<int:id>', delete2020, name="delete20"),

    path('sendToJesus', sendToJesus, name='sendToJesus'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from  . import views

from users.views import *


urlpatterns = [
	#path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('login/', MyLogin, name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
	path('register/', UserFormView.as_view(), name='register'),
	path('register/update/<int:pk>/', UserUpdateView, name='register_update'),
	path('perfil/criar/', ProfileCreateView.as_view(), name='profile_add'),
	path('perfil/update/<int:pk>/', ProfileUpdateView.as_view(), name='profile_update'),

	#
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/registration/password_reset_form.html', email_template_name = 'users/registration/password_reset_email.html', subject_template_name = 'users/registration/password_reset_subject.txt'), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/registration/password_reset_done.html'), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/registration/password_reset_confirm.html'), name='password_reset_confirm'),    
	path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/registration/password_reset_complete.html'), name='password_reset_complete'),

	#path('add_profile/', AddProfileView.as_view(), name='add_profile'),
	#
	path('perfil/administrador/', views.ProfAdminCreate, name='perfil_admin'),
	path('perfil/cordenador/', views.ProfCordenadorCreate, name='perfil_cordenador'),
	path('perfil/professor/', views.ProfProfessorCreate, name='perfil_professor'),
	path('perfil/colaborador/', views.ProfcolaboradorCreate, name='perfil_colaborador'),
	path('perfil/participante/', views.ProfileParticipanteCreate, name='perfil_participante'),

	#
	path('utilizadores/', views.UtilizadoresList, name='utilizadores_list'),
   #path('utilizadores/utilizador_list/', TemplateView.as_view(template_name="users/utilizador_list.html"), name='utilizador_list'),
	path('utilizadores/visualizar/<int:pk>/', UtilizadorDetailView.as_view(), name='detail'),
	path('utilizadores/apagar/<int:pk>/', UtilizadorDeleteView.as_view(), name='delete'),
	path('utilizadores/editar/<int:pk>/', UtilizadorUpdateView, name='update'),
	path('utilizadores/update_estado/<int:pk>/', update_estado, name='update_estado'),
	#
	path('list_profile/', ProfileListView.as_view(), name='list_profile'),
	path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
	#
	path('usuario/', views.UserProfileView, name='user_profile'),
	path('usuario/password_change/', change_password, name='password_change'),
	path('usuario/apagar/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
	path('usuario/editar', views.UserProfileEditView, name='user_profile_edit'),
	path('usuario/update/<int:pk>/', views.UsuarioUpdateView, name='usuario_update'),
	path('usuario/update_perfil/<int:pk>/', Usuario2UpdateView.as_view(), name='usuario2_update'),
	path('usuario/criar_perfil/<int:pk>/', Usuario2CreateView.as_view(), name='usuario2_profile'),
	
	#
	path('update_group/<int:pk>/', GroupUpdateView.as_view(), name='update_group'),
	path('delete_group/<int:pk>/', GroupDeleteView.as_view(), name='delete_group'),
	#
	path('participante/criar/', ParticipantCreateView.as_view(), name='add_participant'),
	#path('add_individual_participant/', IndividualParticipantCreateView.as_view(), name='add_individual_participant'),
	#path('add_participant_group/', ParticipantGroupCreateView.as_view(), name='add_participant_group'),
	#path('panel_of_participant/', ParticipantGroupCreateView.as_view(), name='panel_of_participant'),
	#path('participant_group_add/', ParticipantGroupCreateView.as_view(), name='participant_group_add'),
	#path('secondary_teacher_add/', SecondaryTeacherCreateView.as_view(), name='secondary_teacher_add'),
	#
	path('colaborador/criar/', ColaboratorCreateView.as_view(), name='colaborator_add'),
	path('colaborador/schedule/', ScheduleColaboratorCreateView.as_view(), name='add_schedule_colaborator'),
	#path('colaborador/update/<int:pk>/', ColaboratorUpdateView.as_view(), name='colaborator_update'),
	

	#path('colaborator_list/', ColaboratorListView.as_view(), name='colaborator_list'),
	#
	#path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
	path('docente/criar/', TeacherCreateView.as_view(), name='teacher_add'),
	#
  
	path('cordenador/criar', CoordinatorCreateView.as_view(), name='coordinator_add'),
	#
	path('administrador/criar/', AdministratorCreateView.as_view(), name='administrator_add'),

	#
	path('administrador/update_estado/<int:pk>/', update_estado_adm, name='update_estado_adm'),
    path('professor/update_estado/<int:pk>/', update_estado_tch, name='update_estado_tch'),
	path('colaborador/update_estado/<int:pk>/', update_estado_colab, name='update_estado_colab'),
	path('coordenador/update_estado/<int:pk>/', update_estado_coord, name='update_estado_coord')



]

notificacoes/views.py
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils import timezone

# from django.db.models import Q
from django.http import HttpResponse, JsonResponse

# from django.views.generic import (
#     CreateView,
#     UpdateView,
#     DeleteView,
# )

from datetime import (
    datetime,
    timedelta,
)

from .models import *

from users.models import *

@login_required
def inboxView(request):
    return render(request, template_name='notificacoes/notification_list.html')


def markAsSeen(request, **kwargs):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)

    try:
        ntf = Notification.objects.get(pk=kwargs['pk'])

        if not ntf.canSee(request.user):
            return HttpResponse("forbidden", status=403)

        if ntf.markAsSeen(request.user):
            return HttpResponse("marked as seen", status=200)

        return HttpResponse("something went wrong on the server", status=500)
    except Notification.DoesNotExist:
        return HttpResponse("notification not found", status=404)



def deleteNtf(request, **kwargs):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)

    try:
        ntf = Notification.objects.get(pk=kwargs['pk'])

        if not ntf.canSee(request.user):
            return HttpResponse("forbidden", status=403)

        # test if is author
        if ntf.sender and ntf.sender.pk == request.user.pk:
            ntf.deleteNtf()
            return HttpResponse("deleted for all", status=200)
        else:
            if ntf.deleteForUser(request.user):
                return HttpResponse("deleted for me", status=200)

        return HttpResponse("something went wrong on the server", status=500)
    except Notification.DoesNotExist:
        return HttpResponse("notification not found", status=404)


def setPriority(request, **kwargs):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)

    try:
        ntf = Notification.objects.get(pk=kwargs['pk'])

        if not ntf.canSee(request.user):
            return HttpResponse("forbidden", status=403)

        if ntf.setPriority(request.user):
            return HttpResponse("set priority", status=200)

        return HttpResponse("something went wrong on the server", status=500)
    except Notification.DoesNotExist:
        return HttpResponse("notification not found", status=404)

def resetPriority(request, **kwargs):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)

    try:
        ntf = Notification.objects.get(pk=kwargs['pk'])

        if not ntf.canSee(request.user):
            return HttpResponse("forbidden", status=403)

        if ntf.resetPriority(request.user):
            return HttpResponse("reset priority", status=200)

        return HttpResponse("something went wrong on the server", status=500)
    except Notification.DoesNotExist:
        return HttpResponse("notification not found", status=404)



def getCountNew(request):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)

    count = Notification.countUserNewNotifications(request.user)

    return HttpResponse(count, status=200)



def getNotificationData(request, pk):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)

    try:
        ntf = Notification.objects.get(pk=pk)

        if not ntf.canSee(request.user):
            return HttpResponse(status=403)

        ntf_dict = ntf.createNotificationDict()

        if ntf.sender and not ntf.sender.pk == request.user.pk:
            ntf_dict['seen'] = ntf.wasSeenByUser(request.user)

        ntf_dict['priority'] = ntf.isPriorityToUser(request.user)

        return JsonResponse(ntf_dict)

    except Notification.DoesNotExist:
        return HttpResponse("no notification found", status=404)



def getLastNotifications(request):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)

    all_ntf = Notification.getAllReceivedByUser(request.user)

    data = []
    count_unseen = 0
    for ntf in all_ntf[:5]:
        unseen = ntf.wasSeenByUser(request.user),

        if unseen:
            count_unseen += 1

        if ntf.sender:
            sender_name = ntf.sender.username
        else:
            sender_name = "Sistema"

        data.append({
            "id": ntf.pk,
            "subject": ntf.subject,
            "seen": unseen[0],
            "sender": sender_name,
            "sent_time": ntf.sent_time,
        })


    return JsonResponse({
        "unseenCount": count_unseen,
        "data": data,
    })


def getAllRecievedNotifications(request):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)

    all_ntf = Notification.getAllReceivedByUser(request.user)

    data = []
    for ntf in all_ntf:
        ntf_dict = ntf.createNotificationDict()

        ntf_dict['seen'] = ntf.wasSeenByUser(request.user)
        ntf_dict['priority'] = ntf.isPriorityToUser(request.user)

        data.append(ntf_dict)


    return JsonResponse({
        "data": data,
    })



def getAllSentNotifications(request):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)

    all_ntf = Notification.getAllSentByUser(request.user)

    data = []
    for ntf in all_ntf:
        unseen = ntf.wasSeenByUser(request.user),

        ntf_dict = ntf.createNotificationDict()

        ntf_dict['priority'] = ntf.isPriorityToUser(request.user)

        data.append(ntf_dict)


    return JsonResponse({
        "data": data,
    })




def updateLastFetch(request):
    if not request.user.is_authenticated:
        return HttpResponse("auth required", status=401)


    # TODO: add for custom time/mute
    # time = request.GET.get('time', '')
    # if time:
        # try:

        #     timeInt = int(time)

        #     timeParsed = datetime(year=1970, month=1, day=1) + timedelta(microseconds=timeInt*1000)

        #     Notification.updateUserLastFetchTime(request.user, timeParsed)
        #     return HttpResponse(f"updated to " + timeParsed.__str__(), status=200)
        # except (ValueError, OverflowError):
        #     return HttpResponse("invalid time", status=400)

    Notification.updateUserLastFetchTimeToNow(request.user)
    return HttpResponse("updated", status=200)




from users.models import User
def sendToJesus(request):
    teste = Notification.objects.create(
        subject="Title goes here",
        content="and here the body",
        sent_time=timezone.now(),
        sender=request.user
    )

    NotificationReceiver.objects.create(
        notification=teste,
        receiver=request.user
    )

    return HttpResponse("created", status=200)



def sendMessage(request):
    listUsers = User.objects.all()
    return render(request,
                template_name='notificacoes/sendMessage.html',
                context = {'listaUtilizadores':listUsers}
                )

def sendMessageForm(request, **kwargs):
    listUsers = User.objects.all()
    subject = request.POST["subject"]
    content = request.POST["content"]
    sent_time = timezone.now()
    current_user = request.user
    receiver = request.POST['receiver']
    receiverfinal = User.objects.get(username=receiver)


    notification = Notification(subject=subject, content=content, sent_time=sent_time, sender=current_user)
    notificationReceiver = NotificationReceiver(receiver = receiverfinal, notification = notification)

    notification.save()
    notificationReceiver.save()


    return redirect(reverse('notificacoes:viewInbox') + "?view=sent")

def responseMessage(request, pk):

    return render(request,
                template_name='notificacoes/responseMessage.html',
                context={'Pk':pk}
                )

def responseMessageForm(request, **kwargs):
    pk = request.POST["pk"]
    subject = request.POST["subject"]
    content = request.POST["content"]
    sent_time = timezone.now()
    current_user = request.user
    getNot = Notification.objects.get(id = pk)
    receiver = getNot.sender


    notification = Notification(subject=subject, content=content, sent_time=sent_time, sender=current_user)
    notificationReceiver = NotificationReceiver(receiver = receiver, notification = notification)

    notification.save()
    notificationReceiver.save()


    return redirect(reverse('notificacoes:viewInbox') + "?view=sent")




def notificacoes1(request):

    return render(request,
                template_name='notificacoes/notificacoeslist.html',
                )

def seeAllSended(request):
    utilizador = request.user
    listNotis = Notification.objects.filter(sender = utilizador)

    return render(request,
                 template_name = 'notificacoes/seeSended.html',
                 context = {'listAll' : listNotis})

def delete2020(request, id):
    obj = get_object_or_404(Notification, id=id)

    obj.delete()

    return render(request, "notificacoes/seeSended2.html")

notificacoes/templates/notificacoes/notification_list.html
{% extends 'inscricao/base_with_container.html' %}
{% load static %}
{% load sass_tags %}

{% block title %}Todas as Notificações{% endblock %}

{% block extrahead %}
<link href="{% static 'vendor/bulma/bulma-extensions.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/bulma/bulma-switch.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/bulma/bulma-tagsinput.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/bulma-calendar-master/dist/css/bulma-calendar.min.css' %}" rel="stylesheet">
<link href="{% sass_src 'scss/notification_inbox.scss' %}" rel="stylesheet">
{% endblock %}



{% block path %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}">Início</a></li>
    <li class="breadcrumb-item active" aria-current="page">Notificações</li>
{% endblock %}





{% block content_card %}
<div class="mb-5 pl-5 pr-5">
  <h2 class="title is-3">Notificações</h2>
  <div id="ntf-box">
    <aside>
      <a href="{% url 'notificacoes:sendMessage' %}" class="button is-success">
        <i class="text-white fas fa-plus"> </i> Enviar Notificação
      </a>
      <hr>
      <div id="inboxSideBar" hidden>
        <div id="ntfModeTabs" class="tabs is-toggle is-toggle-rounded is-white">
          <ul>
            <li>
              <a>
                <span class="icon is-small"><i class="fa fa-inbox"></i></span>
                <span>Recebidas</span>
              </a>
            </li>
            <li>
              <a>
                <span class="icon is-small"><i class="fas fa-paper-plane"></i></i></span>
                <span>Enviadas</span>
              </a>
            </li>
          </ul>
        </div>
        <h3 class="title is-4">Filtros</h3>
        <div id="filters">
          <div id="receiveViewFilters" hidden>
            <div class="field">
              <div class="autocomplete control">
                <div class="control has-icons-left is-clearfix">
                  <input id="receiveSearch" class="input my-filter-input" placeholder="Procurar..." type="text" autocomplete="off">
                  <span class="icon is-left">
                    <i class="fas fa-search fa-lg" style="color: rgb(170, 170, 170)" aria-hidden="true"></i>
                  </span>
                </div>
              </div>
            </div>
            <div class="field">
              <input id="receiveOnlyUnseenFilter" type="checkbox" name="receiveOnlyUnseenFilter" class="switch is-rounded is-info">
              <label for="receiveOnlyUnseenFilter">Apenas por ler</label>
              <br><br>
              <input id="receiveOnlyPriorityFilter" type="checkbox" name="receiveOnlyPriorityFilter" class="switch is-rounded is-info">
              <label for="receiveOnlyPriorityFilter">Apenas com prioridade</label>
            </div>
            <div class="field">
              <label for="receiveStartDateFilter">Desde de:</label>
              <div class="autocomplete control">
                <div class="control is-clearfix">
                  <input id="receiveStartDateFilter" class="dayInputFilter input" type="date" autocomplete="off">
                </div>
              </div>
              <label for="receiveEndDateFilter">Até: </label>
              <div class="autocomplete control">
                <div class="control is-clearfix">
                  <input id="receiveEndDateFilter" class="dayInputFilter input" type="date" autocomplete="off">
                </div>
              </div>
            </div>
            <button id="receiveClearFilter" class="button is-danger"><i class="fas has-text-white pr-2 fa-md fa-times" aria-hidden="true"></i>Limpar Filtros</button>
          </div>
          <div id="sentViewFilters" hidden>
            <div class="field">
              <div class="autocomplete control">
                <div class="control has-icons-left is-clearfix">
                  <input id="sentSearch" class="input my-filter-input" placeholder="Procurar..." type="text"
                    autocomplete="off">
                  <span class="icon is-left">
                    <i class="fas fa-search fa-lg" style="color: rgb(170, 170, 170)" aria-hidden="true"></i>
                  </span>
                </div>
              </div>
            </div>
            <div class="field">
              <input id="sentOnlyPriorityFilter" type="checkbox" name="sentOnlyPriorityFilter" class="switch is-rounded is-info">
              <label for="sentOnlyPriorityFilter">Apenas com prioridade</label>
            </div>
            <div class="field">
              <label for="sentStartDateFilter">Desde de:</label>
              <div class="autocomplete control">
                <div class="control is-clearfix">
                  <input id="sentStartDateFilter" class="dayInputFilter input" type="date" autocomplete="off">
                </div>
              </div>
              <label for="sentEndDateFilter">Até: </label>
              <div class="autocomplete control">
                <div class="control is-clearfix">
                  <input id="sentEndDateFilter" class="dayInputFilter input" type="date" autocomplete="off">
                </div>
              </div>
            </div>
            <br>
            <button id="sentClearFilter" class="button is-danger"><i class="fas has-text-white pr-2 fa-md fa-times" aria-hidden="true"></i>Limpar Filtros</button>
          </div>
        </div>
      </div>
      <div id="detailSideBar" hidden>
        <strong >Assunto: </strong>
        <span id="detailSubjectContainer">A Carregar...</span>
        <br>
        <span id="detailDateContainer" class="text-secondary">A Carregar data...</span>
        <br><br>
        <strong >Autor:</strong>
        <span id="detailAuthorContainer">A Carregar...</span>
        <br>
        <strong>Enviado para:</strong>
        <span id="detailReceiversContainer">A Carregar...</span>
      </div>
    </aside>
    <main>
      <div id="controlBar">
        <div id="receiveViewControlBar" hidden>
          <div class="right-buttons-container always-right">
            <span>
              <button id="receiveViewRefreshBtn" class="button"><i class="fas fa-redo"></i><span> a atualizar...</span></button>
            </span>
            <span>
              <button id="receivedPreviousBtn">
                <i class="fas fa-chevron-left fa-lg"></i>
              </button>
              <button id="receivedNextBtn">
                <i class="fas fa-chevron-right fa-lg"></i>
              </button>
            </span>
          </div>
        </div>
        <div id="sentViewControlBar" hidden>
          <div class="right-buttons-container always-right">
            <span>
              <button id="sentViewRefreshBtn" class="button"><i class="fas fa-redo"></i><span>a atualizar...</span></button>
            </span>
            <span>
              <button id="sentPreviousBtn">
                <i class="fas fa-chevron-left fa-lg"></i>
              </button>
              <button id="sentNextBtn">
                <i class="fas fa-chevron-right fa-lg"></i>
              </button>
            </span>
          </div>
        </div>
        <div id="detailViewControlBar" hidden>
          <button id="detailBackButton" class="button is-link"><i style="color: white" class="fas fa-arrow-left"></i> voltar</button>
          <span id="detailViewActionButtons">
            <a id="replyPageBtn">
              <button class="button"><i class="fas fa-reply"></i> responder</button>
            </a>
            <button id="detailSetPriorityBtn" class="button is-warning" hidden><i class="far fa-star"></i>marcar prioridade</button>
            <button id="detailResetPriorityBtn" class="button is-warning" hidden><i class="fas fa-star"></i>remover prioridade</button>
            <button id="detailDeleteBtn" class="button is-danger" data-toggle="modal" data-target="#deleteConfirmModal"><i class="fas fa-trash-alt"></i>Apagar Notificação</button>
          </span>
        </div>
      </div>

      <hr>

      <div id="contentPannel">
        <div id="receiveViewContentPannel" hidden>
          <table id="receiveTable" class="table" data-page-length='100'>
            <thead hidden></thead>
            <tbody></tbody>
          </table>
        </div>
        <div id="sentViewContentPannel" hidden>
          <table id="sentTable" class="table" data-page-length='100'>
            <thead hidden></thead>
            <tbody></tbody>
          </table>
        </div>
        <div id="detailContentPannel" hidden>
          <div class="pr-5">
            <span id="detailContentContainer">A Carregar...</span>
          </div>
          <div hidden style="text-align: center; padding-top: 5rem;">
            <i class="fas fa-exclamation-circle" style="font-size: 4em;"></i>
            <h1 class="title is-3">Ocorreu um erro</h1>
            <h2 class="title is-5">Esta notificação poderá não existir ou então não tem permissão para a ver</h2>
          </div>
        </div>
      </div>

    </main>
  </div>
</div>
{% endblock %}





{% block modals %}
<div class="modal fade" id="deleteConfirmModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmModal"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Apagar Notificação</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Tem a certeza que quer apagar esta notificação?</p>
        <p hidden>Nota: Esta notificação apenas deixara de ser visivel para si.</p>
        <p hidden>Nota: Esta notificação deixara de ser visivel para si e para todos a que foi enviada.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">cancelar</button>
        <button id="deleteConfirmBtn" type="button" class="btn btn-danger" data-dismiss="modal">Apagar Notificação</button>
      </div>
    </div>
  </div>
</div>
{% endblock modals %}






{% block extrajs %}
<script>
  var GET_ALL_RECEIVED_NOTIFICATIONS_URL_PATH = "{% url 'notificacoes:getAllRecievedNotifications' %}";
  var GET_ALL_SENT_NOTIFICATIONS_URL_PATH = "{% url 'notificacoes:getAllSentNotifications' %}";
  var MARK_AS_READ_URL_PATH = "{% url 'notificacoes:markAsSeen' 12345 %}".split("12345");
  var GET_NOTIFICATION_DATA_URL_PATH = "{% url 'notificacoes:getNotificationData' 12345 %}".split("12345");
  var REPLY_PAGE__URL_PATH = "{% url 'notificacoes:responseMessage' 12345 %}".split("12345");
  var SET_PRIORITY_URL_PATH = "{% url 'notificacoes:setPriority' 12345 %}".split("12345");
  var RESET_PRIORITY_URL_PATH = "{% url 'notificacoes:resetPriority' 12345 %}".split("12345");
  var DELETE_NOTIFICATION_URL_PATH = "{% url 'notificacoes:deleteNtf' 12345 %}".split("12345");
  var MY_ID = {{ request.user.pk }};
</script>
<script type="text/javascript" src="{% static 'vendor/bulma/bulma-extensions.min.js'%}"></script>
<script type="text/javascript" src="{% static 'vendor/bulma/bulma-tagsinput.min.js'%}"></script>
<script type="text/javascript" src="{% static 'vendor/bulma-calendar-master/dist/js/bulma-calendar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/DataTables/datatables.min.js'%}"></script>

<script type="text/javascript" src="{% static 'js/notification_inbox.js'%}"></script>
{% endblock extrajs %}