atividades/urls.py
from django.contrib import admin
from django.urls import path
# from .views import ActivityListView
# from .views import activity_list, activity_create
from .views import (ActivityCreateView,
                    ActivityDetailView,
                    ActivityDeleteView,
                    ActivityListView,
                    ActivityListAllView,
                    ActivityDefaultUpdateView,
                    ActivitySessionUpdateView,
                    ActivityMaterialUpdateView,
                    ActivityLocationUpdateView,
                    ConfigActivityView,
                    ConfigActivityCreateView,
                    ConfigActivityUpdateView,
                    MaterialListView,
                    MaterialUpdateView,
                    MaterialCreateView,
                    MaterialCreateView2,
                    MaterialDeleteView,
                    ThemeCreateView,
                    ThemeCreateView2,
                    ThemeListView,
                    ThemeDetailView,
                    ThemeUpdateView,
                    ThemeDeleteView,
                    load_buildings,
                    load_location,
                    delete_session,
                    delete_material,
                    activity_detail_info,
                    get_duration,
                    change_status,
                    modal_fill,
                    load_free_location,
                    request_change,
                    FORMS, )

from .forms import MaterialForm

app_name = 'activity'


urlpatterns = [
    # atividades
    path('', ActivityListView.as_view(), name = 'activity'),
    path('todas/', ActivityListAllView.as_view(), name = 'activity-all'),
    path('propor/', ActivityCreateView.as_view(FORMS), name = 'activity-create'),
    path('<int:pk>/', ActivityDetailView.as_view(), name='activity-detail'),
    path('<int:pk>/delete/', ActivityDeleteView.as_view(), name='activity-delete'),
    path('<int:pk>/updateinfo/', ActivityDefaultUpdateView.as_view(), name='activity-update-default'),
    path('<int:pk>/updatesession/', ActivitySessionUpdateView.as_view(), name = 'activity-session-update'),
    path('<int:pk>/updatematerial/', ActivityMaterialUpdateView.as_view(), name = 'activity-material-update'),
    path('<int:pk>/updatelocation/', ActivityLocationUpdateView.as_view(), name = 'activity-location-update'),

    # config
    path('config/', ConfigActivityView.as_view(), name = 'config-activity'),
    path('config/nova', ConfigActivityCreateView.as_view(), name = 'config-create'),
    path('config/atualizar/', ConfigActivityUpdateView.as_view(), name = 'config-update'),

    # temas
    path('tema/', ThemeListView.as_view(), name='theme-list'),
    path('tema/criar/', ThemeCreateView.as_view(), name='theme-create'),
    path('tema/criartema/', ThemeCreateView2.as_view(), name='theme-create-theme'),
    path('tema/<int:pk>/', ThemeDetailView.as_view(), name='theme-detail'),
    path('tema/<int:pk>/alterar/', ThemeUpdateView.as_view(), name='theme-update'),
    path('tema/<int:pk>/eliminar/', ThemeDeleteView.as_view(), name='theme-delete'),

    # materiais
    path('material/criar/', MaterialCreateView.as_view(), name='material-create'),
    path('material/criarmaterial/', MaterialCreateView2.as_view(), name='material-create-material'),
    path('material/', MaterialListView.as_view(), name='material-list'),
    path('material/<int:pk>/eliminar/', MaterialDeleteView.as_view(), name='material-delete'),
    path('material/<int:pk>/alterar/', MaterialUpdateView.as_view(), name='material-update'),

    #ajax paths
    path('ajax/load-buildings/', load_buildings, name='ajax_load_buildings'),  # <-- this one here
    path('ajax/load-location/', load_location, name='ajax_load_location'),  # <-- this one here
    path('ajax/delete-session/', delete_session, name='ajax_delete-session'),
    path('ajax/delete-material/', delete_material, name='ajax_delete-material'),
    path('ajax/activity_detail_info/',  activity_detail_info, name='ajax_detail-info'),
    path('ajax/change_status/', change_status, name='ajax_change-activity-status'),
    path('ajax/modal_fill/', modal_fill, name='ajax_modal-fill'),
    path('ajax/load_free_location/', load_free_location, name='ajax_load-free-location'),
    path('ajax/get_duration/', get_duration, name='ajax_get-duration'),
    path('ajax/request_change/', request_change, name='ajax_request-change'),
]

dia_aberto/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from .sitemap import StaticViewSitemap
from django.conf.urls import url


sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [

    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}),
    path('', include('inscricao.urls')),
    path('', include('users.urls')),
    path('atividades/', include('atividades.urls')),
    path('', include('config_dia_aberto.urls')),
    path('notificacoes/', include('notificacoes.urls')),
    path('', include('coordenadores.urls')),
    path('colaboradores/', include('colaboradores.urls')),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from  . import views

from users.views import *


urlpatterns = [
	#path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('login/', MyLogin, name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
	path('register/', UserFormView.as_view(), name='register'),
	path('register/update/<int:pk>/', UserUpdateView, name='register_update'),
	path('perfil/criar/', ProfileCreateView.as_view(), name='profile_add'),
	path('perfil/update/<int:pk>/', ProfileUpdateView.as_view(), name='profile_update'),

	#
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/registration/password_reset_form.html', email_template_name = 'users/registration/password_reset_email.html', subject_template_name = 'users/registration/password_reset_subject.txt'), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/registration/password_reset_done.html'), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/registration/password_reset_confirm.html'), name='password_reset_confirm'),    
	path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/registration/password_reset_complete.html'), name='password_reset_complete'),

	#path('add_profile/', AddProfileView.as_view(), name='add_profile'),
	#
	path('perfil/administrador/', views.ProfAdminCreate, name='perfil_admin'),
	path('perfil/cordenador/', views.ProfCordenadorCreate, name='perfil_cordenador'),
	path('perfil/professor/', views.ProfProfessorCreate, name='perfil_professor'),
	path('perfil/colaborador/', views.ProfcolaboradorCreate, name='perfil_colaborador'),
	path('perfil/participante/', views.ProfileParticipanteCreate, name='perfil_participante'),

	#
	path('utilizadores/', views.UtilizadoresList, name='utilizadores_list'),
   #path('utilizadores/utilizador_list/', TemplateView.as_view(template_name="users/utilizador_list.html"), name='utilizador_list'),
	path('utilizadores/visualizar/<int:pk>/', UtilizadorDetailView.as_view(), name='detail'),
	path('utilizadores/apagar/<int:pk>/', UtilizadorDeleteView.as_view(), name='delete'),
	path('utilizadores/editar/<int:pk>/', UtilizadorUpdateView, name='update'),
	path('utilizadores/update_estado/<int:pk>/', update_estado, name='update_estado'),
	#
	path('list_profile/', ProfileListView.as_view(), name='list_profile'),
	path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
	#
	path('usuario/', views.UserProfileView, name='user_profile'),
	path('usuario/password_change/', change_password, name='password_change'),
	path('usuario/apagar/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
	path('usuario/editar', views.UserProfileEditView, name='user_profile_edit'),
	path('usuario/update/<int:pk>/', views.UsuarioUpdateView, name='usuario_update'),
	path('usuario/update_perfil/<int:pk>/', Usuario2UpdateView.as_view(), name='usuario2_update'),
	path('usuario/criar_perfil/<int:pk>/', Usuario2CreateView.as_view(), name='usuario2_profile'),
	
	#
	path('update_group/<int:pk>/', GroupUpdateView.as_view(), name='update_group'),
	path('delete_group/<int:pk>/', GroupDeleteView.as_view(), name='delete_group'),
	#
	path('participante/criar/', ParticipantCreateView.as_view(), name='add_participant'),
	#path('add_individual_participant/', IndividualParticipantCreateView.as_view(), name='add_individual_participant'),
	#path('add_participant_group/', ParticipantGroupCreateView.as_view(), name='add_participant_group'),
	#path('panel_of_participant/', ParticipantGroupCreateView.as_view(), name='panel_of_participant'),
	#path('participant_group_add/', ParticipantGroupCreateView.as_view(), name='participant_group_add'),
	#path('secondary_teacher_add/', SecondaryTeacherCreateView.as_view(), name='secondary_teacher_add'),
	#
	path('colaborador/criar/', ColaboratorCreateView.as_view(), name='colaborator_add'),
	path('colaborador/schedule/', ScheduleColaboratorCreateView.as_view(), name='add_schedule_colaborator'),
	#path('colaborador/update/<int:pk>/', ColaboratorUpdateView.as_view(), name='colaborator_update'),
	

	#path('colaborator_list/', ColaboratorListView.as_view(), name='colaborator_list'),
	#
	#path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
	path('docente/criar/', TeacherCreateView.as_view(), name='teacher_add'),
	#
  
	path('cordenador/criar', CoordinatorCreateView.as_view(), name='coordinator_add'),
	#
	path('administrador/criar/', AdministratorCreateView.as_view(), name='administrator_add'),

	#
	path('administrador/update_estado/<int:pk>/', update_estado_adm, name='update_estado_adm'),
    path('professor/update_estado/<int:pk>/', update_estado_tch, name='update_estado_tch'),
	path('colaborador/update_estado/<int:pk>/', update_estado_colab, name='update_estado_colab'),
	path('coordenador/update_estado/<int:pk>/', update_estado_coord, name='update_estado_coord')



]

atividades/forms.py
from datetime import datetime, date, timedelta

from django import forms
from django.forms import formset_factory
from django.forms.widgets import Select
from django.forms.models import inlineformset_factory, modelformset_factory
from django.db.utils import ProgrammingError
from django.urls import reverse_lazy

from django_addanother.widgets import AddAnotherWidgetWrapper
from bootstrap_datepicker_plus import DatePickerInput



from config_dia_aberto.models import Config
from .models import (Activity, SessionActivity, MaterialActivity,
                    Material, Theme, DaySessionPair, SessionDay, ConfigActivity, Session)




class ConfigActivityForm(forms.ModelForm):
    class Meta:
        model = ConfigActivity
        fields = ['start_time', 'end_time', 'session_interval']

    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        if end_time < start_time:
            msg = u"A hora de término tem de ser superior à hora de iniciação"
            self._errors["end_time"] = self.error_class([msg])

def get_choices_time():
    return [('00:'+str(t),t) for t in range(5, 61, 5)][:-1]

class ActivityForm(forms.ModelForm):

    class Meta:
        model = Activity

        fields = ['name', 'description', 'duration', 'max_participants', 'theme', 'target', 'n_colab']
        widgets = {
            'theme':  forms.CheckboxSelectMultiple(),
            'duration':Select(choices = get_choices_time()),
            'max_participants': forms.NumberInput(attrs={
                'min': 1,
                'max': 120,
            }),
            'n_colab': forms.NumberInput(attrs={
                'min': 0,
                'max': 100,
            })
        }

    def __init__(self, *args, **kwargs):
        super(ActivityForm, self).__init__(*args, **kwargs)
        self.fields['theme'].label = "Tema"

class ThemeForm(forms.ModelForm):
    class Meta:
        model = Theme
        fields = ['name', 'color']

class MaterialSimpleForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['name']

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['name']

class MaterialSessionForm(forms.ModelForm):
    class Meta:
        model = MaterialActivity
        fields = ['material', 'quantity']



# formset para o material
MaterialFormSetFinal = inlineformset_factory(SessionActivity,
                                            MaterialActivity,
                                            fields = ['material', 'quantity'],
                                            can_delete = False,
                                            extra = 1,
                                            widgets = {
                                            'quantity': forms.NumberInput(attrs = {
                                                'min': 1,
                                                'max': 100,
                                            })
                                            },)

def get_day_choices():
    try:
        choices = [(str(t),t) for t in SessionDay.objects.all()]
    except ProgrammingError:
        choices = []
    return choices



class DaySessionPairForm(forms.ModelForm):
    class Meta:
        model = DaySessionPair
        fields = ['day', 'session']
        fields_required = ['day', 'session']
        widgets = {
            'day': Select(choices = get_day_choices()),
            'session':  forms.CheckboxSelectMultiple(),
        }




def get_choices_session():
    res = []
    try:
        [(t.start_time, t.start_time) for t in Session.objects.all()]
        return res
    except:
        return res

DaySessionPairFormSet = inlineformset_factory(SessionActivity,
                                            DaySessionPair,
                                            fields = ['day','session'],
                                            widgets = {

                                                'session': forms.CheckboxSelectMultiple(),
                                            },
                                            can_delete = False,
                                             extra = 1)

atividades/templates/atividades/config_activity/config_activity.html
{% extends 'inscricao/base_with_container.html' %}
{% load static %}
{% load sass_tags %}
{% load filter_is_user_types %}

{% block title %}Configurar definições das Atividades do Dia Aberto{% endblock %}

{% block extrahead %}
{% endblock %}

{% block path %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}">Início</a></li>
    <li class="breadcrumb-item active" aria-current="page">Configuração das Atividades do Dia Aberto</li>
{% endblock %}

{% block content_card %}
<div class="mb-5  pl-5 pr-5 pb-5">
  <div class="row">

    <div class="col-9">
      <h2 class="title is-3">Configurações das Atividades do Dia Aberto</h2>
    </div>
    {% if config %}
    {% if request.user.is_authenticated and request.user|is_user_types:"Administrator" and config.sub_activity_started %}
    <div class="col-3">
      <a class="button is-link is-medium" href="{% url 'activity:config-update' %}" type="button"><i class="text-white fas fa-pencil-alt pr-2"></i>Alterar Configuração</a>
    </div>
    {% endif %}
  </div>
  <div class="container-fluid border-top mt-2 pt-2">
    <h3 class="subtitle is-4">Informações </h3>
    <table class="table table-striped table-sm col-6">
      <tbody>
        <tr>
       <th scope="row">Hora de início das sessões:</th>
          <td>{{ config.start_time }} h</td>
        </tr>
        <tr>
          <th scope="row">Hora de fim das sessões:</th>
          <td>{{ config.end_time }} h</td>
        </tr>
        <tr>
          <th scope="row">Intervalo de tempo entre sessões:</th>
          <td>{{ config.session_interval }} min</td>
        </tr>
      </tbody>
    </table>
    </div>
    {% else %}
    </div>
       <br>
    <h3 class="subtitle is-4">Configuração em falta</h3>
    <br>
    {% if request.user.is_authenticated and request.user|is_user_types:"Administrator" %}
      <a class="button is-success is-medium" href="{% url 'activity:config-create' %}" type="button">Criar Configuração</a>
    {% endif %}
    {% endif %}
  </div>
</div>
{% endblock %}

<!--extra js-->
{% block extrajs %}
{% endblock extrajs %}

atividades/templates/atividades/config_activity/config_activity_form.html
{% extends 'inscricao/base_with_container.html' %}

{% load bootstrap4 %}
{% load static %}
{% load sass_tags %}

{% block title %}Configurar definições das Atividades do Dia Aberto{% endblock %}

{% block extrahead %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
<link rel="stylesheet" type="text/css" href="{% static 'vendor/clockpicker/dist/bootstrap-clockpicker.min.css' %}"/>
{% endblock %}

{% block path %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}">Início</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'activity:config-activity' %}">Configuração do Dia Aberto</a></li>
    <li class="breadcrumb-item active" aria-current="page">Nova Configuração</li>
{% endblock %}


{% block content_card %}
<div class="mb-5 pb-5 container pl-5 pr-5 col-xs-12 col-sm-12 col-md-12 col-lg-6">

  <h2 class="title is-3 text-center">Configurações do Dia Aberto</h2>
  <p class = "text-center">Preencha os campos obrigatórios para criar uma configuração de atividades</p>
  <div class="icon-hr">
        <span></span>
        <div>
            <span>
                <i class="fa fa-cogs" aria-hidden="false"></i>
            </span>
        </div>
        <span></span>
    </div>
  <div class="container-fluid mt-2 pt-2">
   <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="subtitle is-4">Datas Limite</legend>
        {% bootstrap_form form %}
      </fieldset>
      <div class="form-group">
        <a class="button is-dark" href="{% url 'activity:config-activity' %}">Cancelar</a>
        <button class="button is-link float-right" type="submit">Submeter</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

<!--extra js-->
{% block extrajs %}
<script type="text/javascript" src="{% static 'vendor/clockpicker/dist/bootstrap-clockpicker.js'%}"></script>

<script>

$('input').attr('autocomplete', 'off')
var input = $('input:not(:last)').clockpicker({
    placement: 'bottom',
    align: 'left',
    autoclose: true,
});
</script>
{% endblock extrajs %}

atividades/templates/atividades/config_activity/config_activity_form_update.html
{% extends 'inscricao/base_with_container.html' %}

{% load bootstrap4 %}
{% load static %}
{% load sass_tags %}

{% block title %}Configurar definições das Atividades do Dia Aberto{% endblock %}

{% block extrahead %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
<link rel="stylesheet" type="text/css" href="{% static 'vendor/clockpicker/dist/bootstrap-clockpicker.min.css' %}"/>
{% endblock %}

{% block path %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}">Início</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'activity:config-activity' %}">Configuração do Dia Aberto</a></li>
    <li class="breadcrumb-item active" aria-current="page">Alterar Configuração</li>
{% endblock %}


{% block content_card %}
<div class="mb-5  container pb-5 pl-5 pr-5 col-xs-12 col-sm-12 col-md-12 col-lg-6">

  <h2 class="title text-center is-3">Configurações do Dia Aberto</h2>
    <p class = "text-center">Preencha os campos obrigatórios para alterar uma configuração de atividades.</p>
      <div class="icon-hr  icon-hr-edit">
          <span></span>
          <div>
              <span>
                  <i class="fa fa-cogs" aria-hidden="false"></i>
              </span>
          </div>
          <span></span>
      </div>
  <div class="container-fluid  mt-2 pt-2">
   <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="subtitle is-4">Datas Limite</legend>
        {% bootstrap_form form %}
      </fieldset>
      <div class="form-group">
        <a class="button is-dark" href="{% url 'activity:config-activity' %}">Cancelar</a>
        <button class="button is-link float-right" type="submit">Submeter</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

<!--extra js-->
{% block extrajs %}
<script type="text/javascript" src="{% static 'vendor/clockpicker/dist/bootstrap-clockpicker.js'%}"></script>

<script>

$('input').attr('autocomplete', 'off')
var input = $('input:not(:last)').clockpicker({
    placement: 'bottom',
    align: 'left',
    autoclose: true,
});
</script>
{% endblock extrajs %}